services:
#    payment_bridge.example:
#        class: PaymentBridgeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    payment.bridge:
            class: PaymentBridgeBundle\Services\PaymentBridge

    payment.event.listener:
            class:     PaymentBridgeBundle\Listener\Payment
            arguments: [@doctrine.orm.entity_manager, @mailer]
            tags:
                - { name: kernel.event_listener, event: payment.order.done, method: onPaymentOrderDone }
                - { name: kernel.event_listener, event: payment.order.created, method: onPaymentOrderCreated }
                - { name: kernel.event_listener, event: payment.order.load, method: onPaymentLoad }
                - { name: kernel.event_listener, event: payment.order.success, method: onPaymentSuccess }
                - { name: kernel.event_listener, event: payment.order.fail, method: onPaymentFail }